### ISSUE TITLE
No License in project

### ISSUE THREAD

**Issue by ranzbak** [MParygin/v.vga.font8x16#1]
Hi, 

I would like you code in a project for an even open source fpga board.
But since we we are kinda strict with licenses I can't use the code atm.
Could you please license the code (I hope something like MIT / Apache, but it's up to you)

Cheers, Paul Honig

**Comment by MParygin** [comment]
Hi. Paul
You can use this code in any manner
Absolutely

And..I attempt set license


вт, 29 мар. 2022 г. в 01:26, Paul Honig ***@***.***>:

**Comment by MParygin** [comment]
Hi
License is set

**Comment by ranzbak** [comment]
Thank you very much!
